<?php

require_once dirname(__FILE__) . '/../../model/PostRating.php';

/**
 * Test class for PostRating.
 * Generated by PHPUnit on 2011-07-06 at 12:40:52.
 */
class PostRatingTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PostRating
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PostRating;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testGet_prikey().
     */
    public function testGet_prikey() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet_tablename().
     */
    public function testGet_tablename() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
