<?php

require_once dirname(__FILE__) . '/../../model/User.php';

/**
 * Test class for User.
 * Generated by PHPUnit on 2011-07-01 at 14:41:55.
 */
class UserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * Test pull function
     */
    public function testPull() {
        $this->assertNotNull($this->object->set_id(1101));
        $this->assertEquals(1, $this->object->size());
        $this->assertTrue($this->object->pull());
        $this->assertEquals('hovey', $this->object->name);
        $this->assertFalse($this->object->pull());
        $this->assertEquals(0, $this->object->set_id(null)->size());
    }
    
    public function testUpdate() {
        $this->object->set_id(1101);
        $this->assertTrue($this->object->pull());
        $this->assertEquals('hovey', $this->object->name);
        $this->object->name = 'hovey2';
        $this->assertTrue($this->object->push());
        $newobj = new User;
        $newobj->set_id(1101);
        $this->assertTrue($newobj->pull());
        $this->assertEquals('hovey2', $newobj->name);
        $this->assertEquals('hovey2', $this->object->name);
        $newobj->name = 'hovey';
        $this->assertTrue($newobj->push());
        $this->assertEquals('hovey2', $this->object->name);
    }
    
    public function testPrikey() {
        $this->object->id = 1234;
        $this->assertEquals(1234, $this->object->get_id());
    }
    
    /**
     * Generated from @assert () == 'uid'.
     */
    public function testGet_prikey() {
        $this->assertEquals(
                'uid', $this->object->get_prikey()
        );
    }

    /**
     * Generated from @assert () == 'user'.
     */
    public function testGet_tablename() {
        $this->assertEquals(
                'user', $this->object->get_tablename()
        );
    }

}

?>
